# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FirendCircleOfPtotoBrowse' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage'
pod 'SDAutoLayout'
pod 'MJRefresh'
pod 'SVProgressHUD'
  # Pods for FirendCircleOfPtotoBrowse

  target 'FirendCircleOfPtotoBrowseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirendCircleOfPtotoBrowseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
